apiVersion: v1
kind: Service
metadata:
  name: kubetail-expose
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: kubetail
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
