name: Helm Lint

on:
  push:
    branches: [ main]
    paths: ["helm/**"]
  pull_request:
    branches: [ main]
    paths: ["helm/**"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --all --chart-dirs=helm --target-branch ${{ github.event.repository.default_branch }}
